#!/usr/bin/env wish9
# Copyright © 2026 Mark Summerfield. All rights reserved.

const HAS_TLS [expr {![catch { package require tls 2} ]}]
if {$::HAS_TLS} {
    package require http 2
    ::http::register https 443 ::tls::socket
}
if {![catch {file readlink [info script]} name]} {
    const APPPATH [file dirname $name]
} else {
    const APPPATH [file normalize [file dirname [info script]]]
}
tcl::tm::path add $APPPATH
set ::auto_path [linsert $::auto_path 0 [file home]/opt/tcl9lib]

const VERSION 1.2.0
const WISH_FILE [file home]/data/Wishlists.wld
const ISBN_URLS [list \
    https://www.amazon.co.uk/s?k=<ISBN> \
    https://www.speedyhen.com/Search/Results?keyword=<ISBN> \
    https://www.abebooks.co.uk/servlet/SearchResults?isbn=<ISBN> \
]
const WORDS_URLS [list \
    https://www.amazon.co.uk/s?k=<TITLE>+<AUTHOR>&i=stripbooks \
    https://www.speedyhen.com/Search/Results?keyword=<TITLE>+<AUTHOR> \
    https://www.abebooks.co.uk/servlet/SearchResults?sts=t&an=<AUTHOR>&tn=<TITLE>
]

set CAIRO 1
if {[catch { package require tclmcairo }]} { set CAIRO 0 }

package require app

set app [App new]
$app show
